name: Testing

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        py:
          - 3.6
          - 3.8

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.py }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.py }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest -s --cov -vv
